dinx=103
diny=30
dinm=30

disx=250
disy=30

# SUSPOSION      

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)
ent6=ttk.Entry(frameX, text="2", textvariable=v6)
ent6.place(x=dinx, y=diny+dinm*5)
ent7=ttk.Entry(frameX, text="2", textvariable=v7)
ent7.place(x=dinx, y=diny+dinm*6)
ent8=ttk.Entry(frameX, text="2", textvariable=v8)
ent8.place(x=dinx, y=diny+dinm*7)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)
sort6=ttk.Entry(frameX, text="2", textvariable=v6)
sort6.place(x=disx, y=diny+dinm*5)
sort7=ttk.Entry(frameX, text="2", textvariable=v7)
sort7.place(x=disx, y=diny+dinm*6)
sort8=ttk.Entry(frameX, text="2", textvariable=v8)
sort8.place(x=disx, y=diny+dinm*7)



# RIPPAGE

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)

# FRIENMENT

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)
ent6=ttk.Entry(frameX, text="2", textvariable=v6)
ent6.place(x=dinx, y=diny+dinm*5)
ent7=ttk.Entry(frameX, text="2", textvariable=v7)
ent7.place(x=dinx, y=diny+dinm*6)
ent8=ttk.Entry(frameX, text="2", textvariable=v8)
ent8.place(x=dinx, y=diny+dinm*7)
ent9=ttk.Entry(frameX, text="2", textvariable=v9)
ent9.place(x=dinx, y=diny+dinm*8)
ent10=ttk.Entry(frameX, text="2", textvariable=v10)
ent10.place(x=dinx, y=diny+dinm*9)
ent11=ttk.Entry(frameX, text="2", textvariable=v11)
ent11.place(x=dinx, y=diny+dinm*10)
ent12=ttk.Entry(frameX, text="2", textvariable=v12)
ent12.place(x=dinx, y=diny+dinm*11)
ent13=ttk.Entry(frameX, text="2", textvariable=v13)
ent13.place(x=dinx, y=diny+dinm*12)
ent14=ttk.Entry(frameX, text="2", textvariable=v14)
ent14.place(x=dinx, y=diny+dinm*13)
ent15=ttk.Entry(frameX, text="2", textvariable=v15)
ent15.place(x=dinx, y=diny+dinm*14)
ent16=ttk.Entry(frameX, text="2", textvariable=v16)
ent16.place(x=dinx, y=diny+dinm*15)
ent17=ttk.Entry(frameX, text="2", textvariable=v17)
ent17.place(x=dinx, y=diny+dinm*16)
ent18=ttk.Entry(frameX, text="2", textvariable=v18)
ent18.place(x=dinx, y=diny+dinm*17)
ent19=ttk.Entry(frameX, text="2", textvariable=v19)
ent19.place(x=dinx, y=diny+dinm*18)
ent20=ttk.Entry(frameX, text="2", textvariable=v20)
ent20.place(x=dinx, y=diny+dinm*19)
ent21=ttk.Entry(frameX, text="2", textvariable=v21)
ent21.place(x=dinx, y=diny+dinm*20)
ent22=ttk.Entry(frameX, text="2", textvariable=v22)
ent22.place(x=dinx, y=diny+dinm*21)
ent23=ttk.Entry(frameX, text="2", textvariable=v23)
ent23.place(x=dinx, y=diny+dinm*22)
ent24=ttk.Entry(frameX, text="2", textvariable=v24)
ent24.place(x=dinx, y=diny+dinm*23)
ent25=ttk.Entry(frameX, text="2", textvariable=v25)
ent25.place(x=dinx, y=diny+dinm*24)
ent26=ttk.Entry(frameX, text="2", textvariable=v26)
ent26.place(x=dinx, y=diny+dinm*25)
ent27=ttk.Entry(frameX, text="2", textvariable=v27)
ent27.place(x=dinx, y=diny+dinm*26)
ent28=ttk.Entry(frameX, text="2", textvariable=v28)
ent28.place(x=dinx, y=diny+dinm*27)
ent29=ttk.Entry(frameX, text="2", textvariable=v29)
ent29.place(x=dinx, y=diny+dinm*28)
ent30=ttk.Entry(frameX, text="2", textvariable=v30)
ent30.place(x=dinx, y=diny+dinm*29)
ent31=ttk.Entry(frameX, text="2", textvariable=v31)
ent31.place(x=dinx, y=diny+dinm*30)
ent32=ttk.Entry(frameX, text="2", textvariable=v32)
ent32.place(x=dinx, y=diny+dinm*31)
ent33=ttk.Entry(frameX, text="2", textvariable=v33)
ent33.place(x=dinx, y=diny+dinm*32)
ent34=ttk.Entry(frameX, text="2", textvariable=v34)
ent34.place(x=dinx, y=diny+dinm*33)
ent35=ttk.Entry(frameX, text="2", textvariable=v35)
ent35.place(x=dinx, y=diny+dinm*34)
ent36=ttk.Entry(frameX, text="2", textvariable=v36)
ent36.place(x=dinx, y=diny+dinm*35)
ent37=ttk.Entry(frameX, text="2", textvariable=v37)
ent37.place(x=dinx, y=diny+dinm*36)
ent38=ttk.Entry(frameX, text="2", textvariable=v38)
ent38.place(x=dinx, y=diny+dinm*37)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)
sort6=ttk.Entry(frameX, text="2", textvariable=v6)
sort6.place(x=disx, y=diny+dinm*5)
sort7=ttk.Entry(frameX, text="2", textvariable=v7)
sort7.place(x=disx, y=diny+dinm*6)
sort8=ttk.Entry(frameX, text="2", textvariable=v8)
sort8.place(x=disx, y=diny+dinm*7)
sort9=ttk.Entry(frameX, text="2", textvariable=v9)
sort9.place(x=disx, y=diny+dinm*8)
sort10=ttk.Entry(frameX, text="2", textvariable=v10)
sort10.place(x=disx, y=diny+dinm*9)
sort11=ttk.Entry(frameX, text="2", textvariable=v11)
sort11.place(x=disx, y=diny+dinm*10)
sort12=ttk.Entry(frameX, text="2", textvariable=v12)
sort12.place(x=disx, y=diny+dinm*11)
sort13=ttk.Entry(frameX, text="2", textvariable=v13)
sort13.place(x=disx, y=diny+dinm*12)
sort14=ttk.Entry(frameX, text="2", textvariable=v14)
sort14.place(x=disx, y=diny+dinm*13)
sort15=ttk.Entry(frameX, text="2", textvariable=v15)
sort15.place(x=disx, y=diny+dinm*14)
sort16=ttk.Entry(frameX, text="2", textvariable=v16)
sort16.place(x=disx, y=diny+dinm*15)
sort17=ttk.Entry(frameX, text="2", textvariable=v17)
sort17.place(x=disx, y=diny+dinm*16)
sort18=ttk.Entry(frameX, text="2", textvariable=v18)
sort18.place(x=disx, y=diny+dinm*17)
sort19=ttk.Entry(frameX, text="2", textvariable=v19)
sort19.place(x=disx, y=diny+dinm*18)
sort20=ttk.Entry(frameX, text="2", textvariable=v20)
sort20.place(x=disx, y=diny+dinm*19)
sort21=ttk.Entry(frameX, text="2", textvariable=v21)
sort21.place(x=disx, y=diny+dinm*20)
sort22=ttk.Entry(frameX, text="2", textvariable=v22)
sort22.place(x=disx, y=diny+dinm*21)
sort23=ttk.Entry(frameX, text="2", textvariable=v23)
sort23.place(x=disx, y=diny+dinm*22)
sort24=ttk.Entry(frameX, text="2", textvariable=v24)
sort24.place(x=disx, y=diny+dinm*23)
sort25=ttk.Entry(frameX, text="2", textvariable=v25)
sort25.place(x=disx, y=diny+dinm*24)
sort26=ttk.Entry(frameX, text="2", textvariable=v26)
sort26.place(x=disx, y=diny+dinm*25)
sort27=ttk.Entry(frameX, text="2", textvariable=v27)
sort27.place(x=disx, y=diny+dinm*26)
sort28=ttk.Entry(frameX, text="2", textvariable=v28)
sort28.place(x=disx, y=diny+dinm*27)
sort29=ttk.Entry(frameX, text="2", textvariable=v29)
sort29.place(x=disx, y=diny+dinm*28)
sort30=ttk.Entry(frameX, text="2", textvariable=v30)
sort30.place(x=disx, y=diny+dinm*29)
sort31=ttk.Entry(frameX, text="2", textvariable=v31)
sort31.place(x=disx, y=diny+dinm*30)
sort32=ttk.Entry(frameX, text="2", textvariable=v32)
sort32.place(x=disx, y=diny+dinm*31)
sort33=ttk.Entry(frameX, text="2", textvariable=v33)
sort33.place(x=disx, y=diny+dinm*32)
sort34=ttk.Entry(frameX, text="2", textvariable=v34)
sort34.place(x=disx, y=diny+dinm*33)
sort35=ttk.Entry(frameX, text="2", textvariable=v35)
sort35.place(x=disx, y=diny+dinm*34)
sort36=ttk.Entry(frameX, text="2", textvariable=v36)
sort36.place(x=disx, y=diny+dinm*35)
sort37=ttk.Entry(frameX, text="2", textvariable=v37)
sort37.place(x=disx, y=diny+dinm*36)
sort38=ttk.Entry(frameX, text="2", textvariable=v38)
sort38.place(x=disx, y=diny+dinm*37)


# GAZ

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)
ent6=ttk.Entry(frameX, text="2", textvariable=v6)
ent6.place(x=dinx, y=diny+dinm*5)
ent7=ttk.Entry(frameX, text="2", textvariable=v7)
ent7.place(x=dinx, y=diny+dinm*6)
ent8=ttk.Entry(frameX, text="2", textvariable=v8)
ent8.place(x=dinx, y=diny+dinm*7)
ent9=ttk.Entry(frameX, text="2", textvariable=v9)
ent9.place(x=dinx, y=diny+dinm*8)
ent10=ttk.Entry(frameX, text="2", textvariable=v10)
ent10.place(x=dinx, y=diny+dinm*9)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)
sort6=ttk.Entry(frameX, text="2", textvariable=v6)
sort6.place(x=disx, y=diny+dinm*5)
sort7=ttk.Entry(frameX, text="2", textvariable=v7)
sort7.place(x=disx, y=diny+dinm*6)
sort8=ttk.Entry(frameX, text="2", textvariable=v8)
sort8.place(x=disx, y=diny+dinm*7)
sort9=ttk.Entry(frameX, text="2", textvariable=v9)
sort9.place(x=disx, y=diny+dinm*8)
sort10=ttk.Entry(frameX, text="2", textvariable=v10)
sort10.place(x=disx, y=diny+dinm*9)

# DIESEL

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)
ent6=ttk.Entry(frameX, text="2", textvariable=v6)
ent6.place(x=dinx, y=diny+dinm*5)
ent7=ttk.Entry(frameX, text="2", textvariable=v7)
ent7.place(x=dinx, y=diny+dinm*6)
ent8=ttk.Entry(frameX, text="2", textvariable=v8)
ent8.place(x=dinx, y=diny+dinm*7)
ent9=ttk.Entry(frameX, text="2", textvariable=v9)
ent9.place(x=dinx, y=diny+dinm*8)
ent10=ttk.Entry(frameX, text="2", textvariable=v10)
ent10.place(x=dinx, y=diny+dinm*9)
ent11=ttk.Entry(frameX, text="2", textvariable=v11)
ent11.place(x=dinx, y=diny+dinm*10)
ent12=ttk.Entry(frameX, text="2", textvariable=v12)
ent12.place(x=dinx, y=diny+dinm*11)
ent13=ttk.Entry(frameX, text="2", textvariable=v13)
ent13.place(x=dinx, y=diny+dinm*12)
ent14=ttk.Entry(frameX, text="2", textvariable=v14)
ent14.place(x=dinx, y=diny+dinm*13)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)
sort6=ttk.Entry(frameX, text="2", textvariable=v6)
sort6.place(x=disx, y=diny+dinm*5)
sort7=ttk.Entry(frameX, text="2", textvariable=v7)
sort7.place(x=disx, y=diny+dinm*6)
sort8=ttk.Entry(frameX, text="2", textvariable=v8)
sort8.place(x=disx, y=diny+dinm*7)
sort9=ttk.Entry(frameX, text="2", textvariable=v9)
sort9.place(x=disx, y=diny+dinm*8)
sort10=ttk.Entry(frameX, text="2", textvariable=v10)
sort10.place(x=disx, y=diny+dinm*9)
sort11=ttk.Entry(frameX, text="2", textvariable=v11)
sort11.place(x=disx, y=diny+dinm*10)
sort12=ttk.Entry(frameX, text="2", textvariable=v12)
sort12.place(x=disx, y=diny+dinm*11)
sort13=ttk.Entry(frameX, text="2", textvariable=v13)
sort13.place(x=disx, y=diny+dinm*12)
sort14=ttk.Entry(frameX, text="2", textvariable=v14)
sort14.place(x=disx, y=diny+dinm*13)

# REGLOPHORE

ent1=ttk.Entry(frameX, text="2", textvariable=v1)
ent1.place(x=dinx, y=diny)
ent2=ttk.Entry(frameX, text="2", textvariable=v2)
ent2.place(x=dinx, y=diny+dinm)
ent3=ttk.Entry(frameX, text="2", textvariable=v3)
ent3.place(x=dinx, y=diny+dinm*2)
ent4=ttk.Entry(frameX, text="2", textvariable=v4)
ent4.place(x=dinx, y=diny+dinm*3)
ent5=ttk.Entry(frameX, text="2", textvariable=v5)
ent5.place(x=dinx, y=diny+dinm*4)
ent6=ttk.Entry(frameX, text="2", textvariable=v6)
ent6.place(x=dinx, y=diny+dinm*5)
ent7=ttk.Entry(frameX, text="2", textvariable=v7)
ent7.place(x=dinx, y=diny+dinm*6)
ent8=ttk.Entry(frameX, text="2", textvariable=v8)
ent8.place(x=dinx, y=diny+dinm*7)

sort1=ttk.Entry(frameX, text="2", textvariable=v1)
sort1.place(x=disx, y=diny)
sort2=ttk.Entry(frameX, text="2", textvariable=v2)
sort2.place(x=disx, y=diny+dinm)
sort3=ttk.Entry(frameX, text="2", textvariable=v3)
sort3.place(x=disx, y=diny+dinm*2)
sort4=ttk.Entry(frameX, text="2", textvariable=v4)
sort4.place(x=disx, y=diny+dinm*3)
sort5=ttk.Entry(frameX, text="2", textvariable=v5)
sort5.place(x=disx, y=diny+dinm*4)
sort6=ttk.Entry(frameX, text="2", textvariable=v6)
sort6.place(x=disx, y=diny+dinm*5)
sort7=ttk.Entry(frameX, text="2", textvariable=v7)
sort7.place(x=disx, y=diny+dinm*6)
sort8=ttk.Entry(frameX, text="2", textvariable=v8)
sort8.place(x=disx, y=diny+dinm*7)